### ISSUE TITLE
brew installation issues

### ISSUE THREAD

**Issue by sobolevn** [zsh-users/antigen#159]
It is not clear to me how to install `antigen` with `brew` on Mac OS X 10.11.3 the right way. 

Some manuals say (http://macappstore.org/antigen/) that it will be available to use just after installation, but it's not.

```
[13:33:36] sobolev :: MacBook-Pro-Nikita  ➜  ~ » brew info antigen             
antigen: stable 1, HEAD
Plugin manager for zsh, inspired by oh-my-zsh and vundle.
http://antigen.sharats.me/
/usr/local/Cellar/antigen/1 (2 files, 22.3K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/antigen.rb
```

```
[13:36:48] sobolev :: MacBook-Pro-Nikita  ➜  ~ » antigen
zsh: command not found: antigen
```

```
[13:38:11] sobolev :: MacBook-Pro-Nikita  ➜  local/opt/antigen ‹master› » ls `brew --prefix antigen`
INSTALL_RECEIPT.json share
```

```
[13:38:50] sobolev :: MacBook-Pro-Nikita  ➜  local/opt/antigen ‹master› » ls `brew --prefix antigen`/share
antigen.zsh
```

But when I source this file in my `~/.zshrc` it starts to work as excepted. I guess this process (or the right one if I made any mistakes) might be documented somewhere for the future use.

**Comment by danielbayley** [comment]
+1.

```sh
$ brew install antigen
/usr/local/Cellar/antigen/1: 2 files, 22.3K
$ antigen
zsh: command not found: antigen # ?
$ which antigen
antigen not found # *expletives*
```

No 'caveat' or anything…

**Comment by desyncr** [comment]
This issue is solved upstream. Thanks for raising the issue.

**Comment by stoplion** [comment]
Installed latest version antigen via brew and this still happens for me

**Comment by desyncr** [comment]
There is a 'caveat' for it last time I tried it.

```
$ brew info antigen
antigen: stable 1, HEAD
Plugin manager for zsh, inspired by oh-my-zsh and vundle.
http://antigen.sharats.me/
/usr/local/Cellar/antigen/1 (2 files, 22.6K) *
  Built from source on 2016-08-03 at 08:59:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/antigen.rb
==> Caveats
To activate antigen, add the following to your ~/.zshrc:

  source $(brew --prefix)/share/antigen.zsh

```

**Comment by varun19299** [comment]
Seems like that is `source $(brew --prefix)/share/antigen/antigen.zsh` now. Tried on December, 2017.

**Comment by 00guille** [comment]
i have same problem 

```
==> Caveats
To activate antigen, add the following to your ~/.zshrc:
  source /usr/local/share/antigen/antigen.zsh
==> Summary
🍺  /usr/local/Cellar/antigen/2.2.3: 5 files, 79.7KB, built in 4 seconds
CochaPro:~ guillermoahumada$
CochaPro:~ guillermoahumada$   source /usr/local/share/antigen/antigen.zsh
-bash: zmodload: command not found
-bash: autoload: command not found
-bash: /usr/local/share/antigen/antigen.zsh: line 27: syntax error near unexpected token `newline'
-bash: /usr/local/share/antigen/antigen.zsh: line 27: `        { zcompile "$config" } &!' 
```

**Comment by desyncr** [comment]
@00guille You're using bash instead of zsh.

**Comment by KumaCool** [comment]
iterm every time restart command to be executed.`source $(brew --prefix) ...`
help me. thanks!

**Comment by Zaky7** [comment]
type brew info antigen 

It showed me below command and  it solved my issue
` source /usr/local/share/antigen/antigen.zsh`

**Comment by xDhii** [comment]
> type brew info antigen
> 
> It showed me below command and it solved my issue ` source /usr/local/share/antigen/antigen.zsh`

Thank you! Solved for me also!
Didn't find this in any other documentation or even in installation instructions.
