### ISSUE TITLE
PATH gets expanded further and further for nested instances of zsh

### ISSUE THREAD

**Issue by kopp** [zsh-users/antigen#535]
I use antigen v2.1.0 with zsh 5.1.1 under Ubuntu 16.04 with the following in my `~/.zshrc`:
```
source ~/.antigen/antigen.zsh
antigen init ~/.antigenrc
```
my `~/.antigenrc` is
```
± cat ~/.antigenrc
# Load the oh-my-zsh's library.
antigen use oh-my-zsh
 
# Bundles from the default repo (robbyrussell's oh-my-zsh).
# Note: They don't need the prefix 'oh-my-zsh/', because this was 'use'd above.
antigen bundle git
antigen bundle command-not-found
antigen bundle sudo
antigen bundle web-search
antigen bundle common-aliases
antigen bundle colored-man-pages
 
# Syntax highlighting bundle.
antigen bundle zdharma/fast-syntax-highlighting
 
# liquiprompt
antigen bundle nojhan/liquidprompt
 
# Tell Antigen that you're done.
antigen apply
```

Whenever I start a zsh, I have all the tools loaded by antigen (e.g. `liquidprompt`) in my `PATH`.  When I start a zsh inside another zsh, I get these paths duplicated:
```
% echo $PATH | sed 's/:/\n/g' | grep liquidprompt
/home/x/.antigen/bundles/nojhan/liquidprompt
% zsh
% echo $PATH | sed 's/:/\n/g' | grep liquidprompt
/home/x/.antigen/bundles/nojhan/liquidprompt
/home/x/.antigen/bundles/nojhan/liquidprompt
```

Is this intended behavior?  If so, I don't see why it is useful...  If not, this is a bug report :-)

**Comment by desyncr** [comment]
It's not intended. This is due how cache is loaded.

I'm gonna take a look today. Thanks for reporting.

**Comment by desyncr** [comment]
Should be fixed in `develop`. Probably available for `2.2.0`.

**Comment by kopp** [comment]
No, sorry.  I checked out 3c9ff4ecb6e76813f38827651485df75528ee52c but it still persists.

Just to be clear: I started zsh in a terminal that was already running zsh before (i.e. nested) and this produced the issue.

**Comment by desyncr** [comment]
I haven't tried with your specific configuration but this is what I get locally with my configs.

```

 ▲ ~ echo $#path
24

 ▲ ~ zsh        

 ▲ ~ echo $#path
24

 ▲ ~ zsh        

 ▲ ~ echo $#path
24

 ▲ ~ zsh        

 ▲ ~ echo $#path
24

 ▲ ~ echo $SHLVL
4
```

**Comment by desyncr** [comment]
It may be related to caching. Try:

    antigen reset
